#!/usr/bin/env python3
"""
Simple multi-language comment scanner that finds suspicious/robotic comments
and emits a JSON report with suggested rewrites.

Usage:
  python tools/scan_ai_comments.py --root .

This is intentionally conservative and language-agnostic: it looks for common
comment tokens and applies heuristics. Extend the patterns and heuristics as needed.
"""
import argparse
import json
import os
import re
from collections import defaultdict
from pathlib import Path
import hashlib
import textwrap

# Basic configuration
COMMENT_PATTERNS = {
    # file extension: list of (line_comment_prefix, block_comment_start, block_comment_end)
    '.py': [('#', None, None)],
    '.js': [('//', '/*', '*/')],
    '.ts': [('//', '/*', '*/')],
    '.c': [('//', '/*', '*/')],
    '.cpp': [('//', '/*', '*/')],
    '.h': [('//', '/*', '*/')],
    '.java': [('//', '/*', '*/')],
    '.go': [('//', '/*', '*/')],
    '.rs': [('//', '/*', '*/')],
    '.md': [('', None, None)],  # treat whole markdown as comment text
    '.sh': [('#', None, None)],
}

SUSPICIOUS_PHRASES = [
    r'\bAs an AI language model\b',
    r'\bAs an AI\b',
    r'\bI cannot\b',
    r'\bI can\'t\b',
    r'\bI am sorry\b',
    r'\bI\'m sorry\b',
    r'\bUnfortunately\b',
    r'\bThis function does\b',
    r'\bThis file was generated\b',
    r'\bGenerated by\b',
    r'\bTODO\b',
    r'\bFIXME\b',
]
SUSPICIOUS_RE = re.compile('|'.join('(' + p + ')' for p in SUSPICIOUS_PHRASES), re.IGNORECASE)

def is_text_file(path: Path) -> bool:
    try:
        text = path.read_bytes()
    except Exception:
        return False
    return b'\x00' not in text

def extract_comments_from_text(text: str, ext: str):
    results = []
    patterns = COMMENT_PATTERNS.get(ext, [])
    lines = text.splitlines()
    for i, line in enumerate(lines, start=1):
        for (prefix, bstart, bend) in patterns:
            if prefix and line.strip().startswith(prefix):
                results.append((i, line.strip()))
            elif ext == '.md':
                if line.strip():
                    results.append((i, line.strip()))
            elif bstart and bstart in line:
                start = line.find(bstart)
                end = line.find(bend, start + len(bstart)) if bend else -1
                if end != -1:
                    content = line[start+len(bstart):end].strip()
                else:
                    content = line[start+len(bstart):].strip()
                results.append((i, content))
    return results

def humanize_suggestion(comment: str) -> str:
    snippet = comment.strip().strip('#/ *')
    snippet = snippet[:200]
    suggestion = f"Explain intent and constraints. Example: \"This {('module' if len(snippet)<20 else 'function')} implements {snippet}. " \
                 f"It assumes X and does not handle Y. See design/doc.md for details.\""
    return suggestion

def file_hash(path: Path):
    h = hashlib.sha256()
    h.update(path.read_bytes())
    return h.hexdigest()

def scan(root: Path):
    report = {'files': []}
    for p in root.rglob('*'):
        if p.is_dir():
            continue
        ext = p.suffix.lower()
        if ext not in COMMENT_PATTERNS:
            continue
        if not is_text_file(p):
            continue
        try:
            text = p.read_text(encoding='utf-8', errors='replace')
        except Exception:
            continue
        comments = extract_comments_from_text(text, ext)
        suspicious = []
        for lineno, c in comments:
            if SUSPICIOUS_RE.search(c):
                suggestion = humanize_suggestion(c)
                suspicious.append({
                    'line': lineno,
                    'comment': c,
                    'suggestion': suggestion,
                })
        if suspicious:
            report['files'].append({
                'path': str(p.relative_to(root)),
                'hash': file_hash(p),
                'suspicious_comments': suspicious,
            })
    return report

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--root', default='.', help='Repo root to scan')
    parser.add_argument('--out', default='ai_comment_report.json', help='Output JSON report')
    args = parser.parse_args()
    root = Path(args.root).resolve()
    report = scan(root)
    with open(args.out, 'w', encoding='utf-8') as fh:
        json.dump(report, fh, indent=2)
    print(f"Wrote report to {args.out}. Files flagged: {len(report['files'])}")

if __name__ == '__main__':
    main()